### ISSUE TITLE
[Enhancement] Make OutlierDetection params configurable

### ISSUE THREAD

**Issue by kenakamu** [istio-ecosystem/admiral#104]
Is there anyway to set outlierDetection? It seems to be hardcoded at the moment, but can we use GTP or other RD to define it?

```yaml
outlierDetection:
      baseEjectionTime: 120s
      consecutive5xxErrors: 10
      interval: 5s
```
