### ISSUE TITLE
[BUG] Unable to use Admiral with Istio 1.6 installed through IstioOperator

### ISSUE THREAD

**Issue by wmgroot** [istio-ecosystem/admiral#121]
**Describe the bug**
The multi-cluster setup for the IstioOperator automatically creates an EnvoyFilter that rewrites .global traffic. This conflicts with Admiral, which contains instructions to remove the EnvoyFilter. However, in the declarative setup for the IstioOperator, it is assumed that all configuration changes to Istio should be handled in its declarative spec.

For example, here is our IstioOperator config:
```
# https://istio.io/latest/docs/setup/additional-setup/cni/#basic-installation
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  # https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec
  addonComponents:
    grafana:
      enabled: true
    istiocoredns:
      enabled: true

  components:
    cni:
      enabled: true
    egressGateways:
      - name: istio-egressgateway
        enabled: true

  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"

    global:
      controlPlaneSecurityEnabled: true
      multiCluster:
        enabled: true
```

**Steps To Reproduce**
Install Istio 1.6+ using the IstioOperator (I used 1.6.5).
Follow the pre-req steps here: https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md

**Expected behavior**
I think there should be a documented way to do at least one of the following:
* Disable the EnvoyFilter through the IstioOperator spec.
* Reconfigure the EnvoyFilter through the IstioOperator spec (to not conflict with Admiral).
* Configure Admiral to not conflict with the EnvoyFilter installed with the IstioOperator.

Maybe there is a better solution.

For what it's worth, when I slept the IstioOperator controller, removed the EnvoyFilter, and tested Admiral on 1.6, it appeared to work as intended.
