### ISSUE TITLE
Example Service Entry load balancing issue and mTLS connection

### ISSUE THREAD

**Issue by iandyh** [istio-ecosystem/admiral#124]
**Describe the bug**
This is not a bug for usage of admiral per se. I am following the docs: https://istio.io/latest/blog/2020/multi-cluster-mesh-automation/ to understand the idea behind Admiral but encountered the following issue:

1. After creating the service entry:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-test
  namespace: caas-sentinel
spec:
  endpoints:
  - address: sample-app.caas-sentinel.svc.cluster.local
    locality: jpe1/jpe1b
    ports:
      http: 80
  hosts:
  - productpage.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  addresses:
  - 240.0.0.10
  resolution: DNS
```

the Envoy configuration does not look correct to me:
```
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "sample-app.caas-sentinel.svc.cluster.local",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          }
         ],
         "load_balancing_weight": 1
        }
```
After I changed to using STATIC and actual pod IP, the configuration looks correct. sidecar proxy will do the direct pod load balancing. I am not sure whether this is a bug(probably by Istio) or by design. But it will be great if someone can help to confirm. 

Second issue is, with the same service entry above, the mTLS connection to `sample-app.caas-sentinel` does not work. I got the `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error.

**Steps To Reproduce**
Istio 1.6
Create above service entry
Turn on target remote service mTLS as shown here: https://istio.io/latest/docs/tasks/security/authentication/authn-policy/

**Expected behavior**
sidecar proxy should do the pod load balancing instead of calling the service FQDN directly.
mTLS should work with local service.

Thanks a lot for your help!
