### ISSUE TITLE
[BUG] The GlobalTrafficPolicy doesn't failover when weights declared

### ISSUE THREAD

**Issue by wenxian** [istio-ecosystem/admiral#134]
**Describe the bug**
If the weight is declared, the 10 times of consecutive5xxErrors won't failover to the other region

**Steps To Reproduce**
```
apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-admiral-sample
  namespace: sample-admiral
  labels:
    env: default
    identity: webapp-sample-admiral
spec:
  policy:
  - dns: default.webapp-sample-admiral.global
    lbType: 1 #0 represents TOPOLOGY, 1 represents FAILOVER
    target:
    - region: us-west-2
      weight: 10
    - region: us-east-1
      weight: 90
```

**Expected behavior**
If a service returns 10 times 500, it won't get kicked off when GTP  Weight(90 / 10 ) applied. 

Without GTP, the  failover will work with 10 consecutive 500 errors
