### ISSUE TITLE
Services are not synchronized without a specific Dependency

### ISSUE THREAD

**Issue by krjensen** [istio-ecosystem/admiral#145]
After deploying a base Admiral setup for two k8s clusters, nothing is synced between clusters.
When I create a specific `Dependency` the sync works

```
---
apiVersion: admiral.io/v1alpha1
kind: Dependency
metadata:
  name: dependency
  namespace: admiral
spec:
  source: Service-a
  identityLabel: identity
  destinations:
    - Service-b
```

Reading the documentation it states:
"Dependency is optional and a missing dependency for a service will result in an Istio configuration for that service pushed to all clusters."

So I would expect all services to be synchronized across all clusters, when no Dependency is created. 

Is also says her: https://github.com/istio-ecosystem/admiral/blob/master/docs/Architecture.md
"If the wild card and specific dependency object are both present any service not matching a specific rule will be sync to all clusters"

But no information about, how to create such a wild card dependency...

/Kristian
