### ISSUE TITLE
[BUG] service name http-{prefix} not working

### ISSUE THREAD

**Issue by maieve** [istio-ecosystem/admiral#150]
connect(O) Service Entry(O)
```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
    identity: nginx
spec:
  ports:
    - name: http
       protocol: TCP
       port: 80
       targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: None
```
Connect(X) Service Entry(X)
```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
    identity: nginx
spec:
  ports:
    - name: http-dev #or grpc
       protocol: TCP
       port: 80
       targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: None
```
