### ISSUE TITLE
[BUG] k8s service's Target port and Port being different causes wrong port to be picked up

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#164]
**Describe the bug**
If a k8s service's target port is different from the port field then the right port is not picked up

**Steps To Reproduce**
Having the following objects will help reproduce the error:

k8s service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeting
    identity: greeting
  name: greeting
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: greeting
```

k8s Deployment:
```
...
  spec:
      template:
         annotations:
              traffic.sidecar.istio.io/includeInboundPorts: "8080"
...
```

The above configuration doesn't result in a port match causing invalid service entry to be generated.

**Expected behavior**
