### ISSUE TITLE
[BUG] Multi cluster case's sample load balanced not work with greeting sample apps

### ISSUE THREAD

**Issue by manmaujin2** [istio-ecosystem/admiral#167]
When I try to test the multiple cluster sample as below document and found that the remote cluster greeting app application does not have "admiral.io/env: stage" annotation so the service entry stage.greeting.global-se doesn't have Cluster 2's istio-ingressgateway address. After I added back the annotation in remote cluster greeting app then the service entry i.e.  stage.greeting.global-se success to added cluster 2 istio-ingressgateway address.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2021-01-29T06:44:06Z"
  generation: 970
  labels:
    identity: greeting
  name: stage.greeting.global-se
  namespace: admiral-sync
spec:
  addresses:
  - 240.0.10.2
  endpoints:
  - address: 10.224.241.137
    locality: eastasia
    ports:
      http: 15443
  - address: greeting.sample.svc.cluster.local
    locality: eastasia
    ports:
      http: 80
  hosts:
  - stage.greeting.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
```

(Ref: https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md#verify)

However, when I trigger below command in cluster 1 to test the apps for load balancing. It always return cluster 1 greeting app payload i.e. "Hello World! - Admiral!!" and never return remote cluster (cluster 2) payload i.e.  "Remote cluster says: Hello World! - Admiral!!".

`kubectl exec --namespace=sample -it $(kubectl get pod -l "app=webapp" --namespace=sample -o jsonpath='{.items[0].metadata.name}') -c webapp -- curl -v http://stage.greeting.global
`

Anyone has idea ?
