### ISSUE TITLE
[FEATURE] Support argo rollouts canary for admiral generated endpoints

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#183]
**Is your feature request related to a problem? Please describe.**
Admiral generated endpoints do not honor the [canary deployment strategy](https://argoproj.github.io/argo-rollouts/features/canary/) of [Argo rollouts](https://argoproj.github.io/argo-rollouts/)

**Describe the solution you'd like**
Implement canary deployment strategy with [host based traffic splitting](https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/#host-level-traffic-splitting). This requires i) Generating ServiceEntry that has both `stable` and `desired` endpoints (services) and ii) Updating weights based on the virtual service that is updates by the rollouts controllers as the canary progresses.

**Example**

`Argo Rollout` definition

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-poc3
spec:
  ...
  strategy:
    canary:
      canaryService: mesh-rollout-poc3-appd-desired-service  # required
      stableService: mesh-rollout-poc3-appd-stable-service  # required
      trafficRouting:
        istio:
          virtualService:
            name: rollout-poc3-vs   # required
            routes:
            - primary            # optional if there is a single route in VirtualService, required otherwise
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
```

`Virtual Service` updated by `Argo rollouts controller`

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-poc3-vs
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio-rollout.dev.argoproj.io
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: mesh-rollout-poc3-appd-stable-service # referenced in canary.stableService
      weight: 60
    - destination:
        host: mesh-rollout-poc3-appd-desired-service # referenced in canary.canaryService
      weight: 40
```

`ServiceEntry` generated by `Admiral`

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    alpha.istio.io/identity: Intuit.dev.deploy.meshrolloutpoc3
  name: rollout-poc3-se
  namespace: admiral-sync
spec:
  addresses:
  - 240.0.99.181
  endpoints:
  - address: mesh-rollout-poc3-appd-stable-service.dev-deploy-meshrolloutpoc3-usw2-e2e.svc.cluster.local
    locality: us-west-2
    ports:
      http: 8090
    weight: 60
  - address: mesh-rollout-poc3-appd-desired-service.dev-deploy-meshrolloutpoc3-usw2-e2e.svc.cluster.local
    locality: us-west-2
    ports:
      http: 8090
    weight: 40
  hosts:
  - e2e.intuit.dev.deploy.meshrolloutpoc3.mesh
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
```
