### ISSUE TITLE
[FEATURE] - Add an ability to provide a mesh service that acts as a proxy through which dependencies should be accessed 

### ISSUE THREAD

**Issue by shriramsharma** [istio-ecosystem/admiral#278]
**Is your feature request related to a problem? Please describe.**
Need the ability to automatically forward requests to a mesh dependency through a proxy service. 

**Describe the solution you'd like**
Create a new CRD that contains the configuration of how a destination can be reached through a given proxy. The configuration also provides the ability to generate additional hostnames through which a service can be called.

Example CRD:
```
apiVersion: admiral.io/v1alpha1
kind: DependencyProxy
metadata:
  name: dependency-proxy-example
  namespace: admiral
  annotations:
     admiral.io/env: stage
spec:
  destination:
    identity: greeting
    dns_suffix: "xyz"
    dns_prefix: 
        - "test00.foo"
        - "test01.bar"
  proxy:
    identity: nginx-proxy
```

This generates the following ServiceEntry
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: stage.nginx.global-se
spec:
  addresses:
  - 240.0.10.1
  endpoints:
  - address: nginx-gw-svc.default.svc.cluster.local
    locality: us-west-2
    ports:
      http: 80
  hosts:
  - test00.foo.stage.greeting.xyz
  - test01.bar.stage.greeting.xyz
```
