### ISSUE TITLE
[BUG] Always route to local instance of a service from istio-ingressgateway

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#62]
**Describe the bug**
When a service name is accessed in a cluster, it's possible for it to bounce between clusters.

**Steps To Reproduce**
Deploy Service 1 to Cluster 1 and Cluster 2
Deploy Service 2 to Cluster 2 
Make a call from Service 2 to Service 1 using `global` name created by admiral
Notice that some of the calls made from Service 2 to Service 1 take very long time. This is because at the `istio-ingressgateway` they might be routed back to the original cluster where the request is originating from as that's also a possible destination for that service.

**Expected behavior**
Service calls using `global` names should not bounce between clusters.

`Proposed solution:`
Create a virtual service that always routes calls to the local instance of a service and attach it to `istio-ingressgateway` gateway
`Example:`
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default.greeting.global-default-vs
  namespace: admiral-sync
spec:
  exportTo:
  - '*'
  gateways:
  - istio-multicluster-ingressgateway
  hosts:
  - default.greeting.global
  http:
  - route:
    - destination:
        host: greeting.sample.svc.cluster.local
        port:
          number: 8080
```
