### ISSUE TITLE
Missing name in service port 

### ISSUE THREAD

**Issue by jwebb49** [istio-ecosystem/admiral#7]
If the name field is missing in the service port definition then the service entry is generated without a port name and is invalid. 

Example
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    identity: nginx
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
```
